name: Bug Report
description: Create a report to improve maturity of the spec!
labels: ["bug", "triage"]
body:
  - type: textarea
    id: what
    attributes:
      label: What's wrong?
      placeholder: Reasons could be contradictions (internally or to external standards), ambiguities, wrong schema files, writing
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why is this a bug?
      description: Also tell us, what did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: how
    attributes:
      label: How could it be fixed?
      description: Feel free to suggest and weigh several resolution strategies. Omit if obvious.
  - type: textarea
    id: context
    attributes:
      label: More context
      description: If applicable, add additional info to help explain your problem.
  - type: markdown
    attributes:
      value: |
        _Please be sure to take a look at
        our [contribution guidelines](https://github.com/eclipse-dataspace-dcp/decentralized-claims-protocol/blob/main/CONTRIBUTING.md) and
        our [PR etiquette](https://github.com/eclipse-dataspace-dcp/decentralized-claims-protocol/blob/main/pr_etiquette.md)._