@startuml
!pragma layout smetana

!include diagram.styles.puml

autonumber

box "Client Entity"
participant "Client" as C
participant "Secure Token Service" as STS
participant "DID Service" as DS
participant "Credential Service" as CS
end box

box "Verifier Entity"
participant "Verifier" as V
end box

C -> STS: request
STS -> C: response incl. access token

C -> V: request w/ self-issued id token incl. access token
DS <- V: resolve DID
DS -> V: DID document response
CS <- V: request w/ self-issued id token incl. access token
CS ->V: VP response
C <- V: response
@enduml