@startuml
!pragma layout smetana

!include diagram.styles.puml

autonumber

box "Client Entity"
participant "Client" as C
participant "Secure Token Service" as STS
participant "DID Service" as DS
participant "Credential Service" as CS
end box

box "Issuer Entity"
participant "Issuer Service" as IS
end box

C -> STS: Self-Issued ID token request
STS -> C: Token response w/ access token
C -> IS: Request credential(s) using Self-Issued ID token
DS <- IS: Resolve DID
DS -> IS: DID document response
C <- IS: Ack
CS <- IS: (async) Write credential(s)\n w/ access token
CS -> CS: Validate token and\n store credentials


@enduml
