@startuml
!pragma layout smetana

!include diagram.styles.puml

autonumber

box "Client Entity"
participant "Client" as C
participant "Secure Token Service" as STS
participant "DID Service" as DS
participant "Credential Service" as CS
end box

box "Issuer Entity"
participant "Issuer Service" as IS
end box

C -> STS: request
STS -> C: response incl. access token
C -> IS: request credential(s) w/ self-issued ID token incl. access token
DS <- IS: resolve DID
DS -> IS: DID document response
C <- IS: ack
CS <- IS: (async) write credential(s)\n w/ self-issued ID token access token
CS -> CS: Validate token and\n store credentials

@enduml
