@startuml
!pragma layout smetana

!include diagram.styles.puml

autonumber

box "Client Entity"
participant "Client" as C
participant "Secure Token Service" as STS
participant "Credential Service" as CS
end box

box "Verifier Entity"
participant "Verifier" as V
end box

C -> STS: SI token request
STS -> C: Token response w/ access token

C-> V: Request w/ si token and access token
V-> CS: request w/ access token
CS ->V: VP response
@enduml
