name: Verify Artifacts

on:
  push:
    branches:
      - main
    paths:
      - "artifacts/**"  
  workflow_dispatch:

  pull_request:
    paths:
      - "artifacts/**"

jobs: 
  verify-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-java
      - name: Run Checkstyle
        working-directory: ./artifacts
        run: |
          ./gradlew checkstyleMain checkstyleTest

  verify-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java
      - name: Checks artifacts
        working-directory: ./artifacts
        run: |
          ./gradlew test
